Algoritmo "VERIFICA_POSITIVO_NEGATIVO"
// Funcao   : [Verificar se um valor é negativo ou positivo]
// Autor(a)   : Isaac Martins
// Data atual  : 19/03/2024
Var
   _verificaValorNegativo: real
Inicio
   escreva ("Digite um valor: ")
   leia (_verificaValorNegativo)

   se _verificaValorNegativo < 0 entao
      escreva ("O VALOR DIGITADO É NEGATIVO!")
   senao
      escreva ("O VALOR DIGITADO É POSITIVO!")
   fimse
Fimalgoritmo