Algoritmo "Dividir_Numeros"
// Funcao   : [Fazer a Divisão de dois numeros]
// Autor(a)   : Isaac Martins
// Data atual  : 14/03/2024
Var
   num1:inteiro
   num2:inteiro
   total:real
Inicio
      escreva ("Escreva um numero: ")
      leia (num1)
      escreva ("Escreva outro numero: ")
      leia (num2)
      total <- num1 / num2
      escreval ("A divisão dos numeros é:", total)
Fimalgoritmo